[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my-autogen-project"
version = "0.1.0"
description = "A description of your project."
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "chainlit>=2.6.0",
    "bcrypt>=4.0.0",
    "asyncpg>=0.29.0",
    "sqlalchemy>=2.0.0",
    "autogen-ext[mcp]==0.6.4",
    "autogen-agentchat==0.6.4",
    "autogen-core==0.6.4", 
    "autogen-ext==0.6.4",
    "autogen_ext[openai]==0.6.4"
]

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.25.0",
    "aiosqlite>=0.19.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short" 